using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace BlazorSampleApplication.DbModels;

public partial class BlazorToDoContext : DbContext
{
    public BlazorToDoContext()
    {
    }

    public BlazorToDoContext(DbContextOptions<BlazorToDoContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Todo> Todos { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=LAPTOP-FPNQ81MI\\SQLEXPRESS;Initial Catalog=BlazorToDo\n;TrustServerCertificate=true; Integrated Security=SSPI");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Todo>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedOnAdd()  // This indicates the value is generated by the database
            .UseIdentityColumn();   // This specifically configures it as a SQL Server identity 

            entity.Property(e => e.Description)
                .HasMaxLength(250)
                .HasColumnName("description");
            entity.Property(e => e.IsDone).HasColumnName("isDone");
            entity.Property(e => e.Title)
                .HasMaxLength(50)
                .HasColumnName("title");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
